
[font]
normal.family="Fira Code"
normal.style="Retina"
size=10.0


[window]
opacity=0.8
decorations="Full"
blur=true

[terminal.shell]
program="/usr/bin/zsh"
args=["-l", "-c", "tmux attach || tmux"]
